name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android-sdk@v2
      with:
        sdk-version: 30
        ndk-version: 21.4.7075529

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: tradingview-app-release
        path: app/build/outputs/apk/release/app-release.apk
